FORMAT: 1A
HOST: http://api.britishgas.co.uk/v1

# Product Bundles 

# Data structures

## Data (object, fixed)
- `id`: 1234 (string) - Entity Id
- `type` (string) - Entity type

## Links (object)
- `self` (string)
- `related` (string)

## Relationship (object)
- `data` (Data) - Data of an entity relationship

## TelephoneNumber (object)

+ number: 0738123456 (string, required) - Telephone number
+ type (enum, optional) - Type of telephone number (`home`, `work` or `mobile`)
    + home (string)
    + work (string)
    + mobile (string)
    + Default: `home`
+ primary: false (boolean, optional)
    + Default: false

## Customer (object)

+ title: Mr (string, required) - Title of customer
+ `first-name`: George (string, required) - First name of customer
+ `middle-name`: Walsh (string,optional) - Middle name of the customer
+ surname: Bush (string, required) - Surname of customer
+ `date-of-birth`: `2008-09-15T15:53:00+05:00` (string, required) - Date of birth for the customer (expressed in ISO 8601 format)
+ `telephone-numbers` (array[TelephoneNumber], required) - All telephone details of customer.
+ `interested-in-smart-meter`: true (boolean, optional) - Indicator to specify if customer has expressed interest in smart meters
+ email: kjones@gmail.com (string, required)
+ `multi-premise-landlord`: true (boolean, optional) - Indicator to specify if customer has multi premise landlord accounts in any of the premise.
+ `contract-partner`: 1607645127 (string, optional) - contract partner/owner number of the customer.
+ ucrn: `303612345678` (string, optional) - Unique Customer Reference Number - this may or may not be different to the id of the customer depending on how long they have been a customer of British Gas. 
+ `home-move-eligibility`: true (boolean,optional) - true or false to verify either eligible for home move process.


## Bundles (object)
+ `is-address-used`: `false` (boolean, required) - true if already product bundle assingned for address otherwise false
+ bundles (array[Bundle], optional) - list of allowed bundles if is-addresss-used is false otherwise null

## Bundle (object)
+ `id`: 002 (string, required) - id of bundle.
+ `boile-code`: CBLR0002 (string, required) - code of bundle.
+ `boiler-name`: Valiant ecoTech plus combi boiler (string, required) - name of boiler
+ `total-gross-price`: 2599.00 (string, optional) - total gross price of bundle
+ `total-bundle-Price`: 2599.00 (string, optional) - total price of bundle
+ `total-price-after-discount`: 1899.00 (string, optional) - total price of bundle after discount
+ `total-discount`: 700.00 (string, optional) - total discount of bundle
+ `boiler-price`: 1149.00 (string, optional) - price of boiler
+ `installation-price`: 1114.00 (string, optional) - price of bundle installation
+ extras (array[Extra], optional) - Extras with bundle product
+ allowances (array[Allowance], optional) - allowances of bundle

## Extra (object)
+ code: AW002 (string, required) - code of extra's.
+ name: Powerflush (string, required) - name of extra's.
+ amount: 500.00 (string, required) - price of extra's.
+ required: false (boolean, required) - need of extra's.

## Allowance (object)
+ code: AW002 (string, required) - code of allowance type
+ name: £500.00 off your powerflush (string, required) - name of allowance
+ amount: 500.00 (string, required) - price of allowance

## BundleOrder (object)
+ `is-address-used`: `false` (boolean, required) - true if already product bundle assingned for address otherwise false
+ `as-best-of-identified`: `I am not Sure`
+ `lead-channel`: `Online`
+ `residence-status`: `Owner`
+ `product-interest`: `Online Boiler`
+ `is-home-care`: `true` - to identify if customer is already hom
+ `is-power-flush`: `true` 
+ `fuel-type`: `Gas` - fuel type used by appliances
+ bundle (Bundle) - Selected bundles and extras by customer


## AddressRelationship (object)

+ links (object, required)
   + self: `http://api.britishgas.co.uk/v1/customers/3612345678/relationships/correspondenceAddress` (string, required)
   + related: `http://api.britishgas.co.uk/v1/customers/3612345678/correspondenceAddress` (string, required)
+ data (array[Relation], required)

## CustomerRelationship (object)

+ links (object, required)
   + self: `http://api.britishgas.co.uk/v1/customers/3612345678/relationships/premises` (string, required)
   + related: `http://api.britishgas.co.uk/v1/customers/3612345678/premises` (string, required)
+ data (array[Relation], required)

## NotificationRelationship (object)

+ links (object, required)
   + self: `http://api.britishgas.co.uk/v1/customers/3612345678/relationships/notifications` (string, required)
   + related: `http://api.britishgas.co.uk/v1/customers/3612345678/notifications` (string, required)
+ data (array[Relation], required)

## Relation

+ id: 12346 (string, required) - Id of the resource.
+ type (string, required) - Type of the resource.

## ProductBundleResource (object)

+ id: `3612345678` (string) - Unique identifier for a customer, bp number, not ucrn
+ type: customers (string) - the resource type
+ attributes (Bundles) - attributes of the resource

## Group Product Bundles
Product Bundles represents package of multiple products for Online product sales. When you retrieve a bundle, eligible extra and allowances will be included by default.

>Note : `GET /product-bundles` supports to verify existing lead for given address, if only address id will be passed without bundle and extra's then it will be validate addess.If already any bundle associated with adress then return back the error response with empty bundle list.

## Product Bundles [/v1/product-bundles]

+ Attributes (ProductBundleResource)

## get all bundles [GET /v1/product-bundles]

Retrieves all product-bundles

+ Request

    + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            identity-bundle: {"address-id": "08937e42-49f0-4e11-90de-343c6b7f73c9", "bundles": [bundle1,bundle2], "isHomeCare": "false", "isPowerFlush": "false","extras":"[extra1,extra2]"}

+ Response 200 (application/vnd.api+json)

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - version of the json api specification.
        + data (array[ProductBundleResource]) - the document’s “primary data”

+ Request Associated Bundle found with Address

    + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            identity-bundle: {"address-id": "08937e42-49f0-4e11-90de-343c6b7f73c9", "bundles": null, "isHomeCare": "false", "isPowerFlush": "false","extras":"null"}

+ Response 404 (application/vnd.api+json)

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - version of the json api specificaiton.
        + errors (array)
            + (object)
               + id: 1467732747181 (string, required) - a unique identifier for this particular occurrence of the problem.
               + detail: `error.address.already.has-lead` (string) - a human-readable explanation specific to this occurrence of the problem.
               + status: 404 (string) - the HTTP status code applicable to this problem, expressed as a string value.


+ Request To Verify if addess has any existing bundle associated- bundle list will be null.

    + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca


+ Response 200 (application/vnd.api+json)

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - version of the json api specificaiton.
        + data (ProductBundleResource) - the document’s “primary data”


+ Request Unable to retrieve bundle

    + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            
+ Response 500

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - specification version.
        + errors (array)
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `read bundle failed` (string).
               + status: 500 (string) - character-text equivalent of HTTP code.

## create a new customer [POST /v1/bundle-order]

+ Request

   + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca

   + Attributes
       + data (object, required)
           + type: bundle-order (string)
           + attributes (BundleOrder, required)
           + relationships (object) - related resources for customers
                + `address` (AddressRelationship)
                    + data (object, required)
                        + id: `08937e42-49f0-4e11-90de-343c6b7f73c9` (string) - Id of related address
                        + type: `addresses` (string) - type of resource
                + `customer` (CustomerRelationship)
                    + data (object, required)
                        + id: `3612091619` (string) - Id of related customer
                        + type: `customers` (string) - type of resource

+ Response 201

   + Header

            Content-Type: application/vnd.api+json
            Location: api/secure/customers/12345

   + Attributes
       + data (object, required)
         + type: customers (string)
         + id: 12345 (string)
         + attributes
                + title: Mr
                + `first-name`: George
                + surname: Bush
                + `date-of-birth`: `2008-09-15T15:53:00+05:00`
                + `telephone-numbers` (array)
                    + number: 01132578895, type: home, primary: true
                    + number: 073817638, type: mobile
                + `interested-in-smart-meter`: true (boolean)
                + email: kjones@gmail.com
         + relationships (object) - related resources for customers
            + `correspondence-address` (AddressRelationship)
                + data (object, required)
                    + id: `08937e42-49f0-4e11-90de-343c6b7f73c9` (string) - Id of related address
                    + type: `addresses` (string) - type of resource
       + links (object)
            + self: `http://britishgas.co.uk/v1/customers/12345`
            
+ Request input validation errors

   + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca

   + Attributes
       + data (object, required)
           + type: customers (string)
           + attributes
                + `interested-in-smart-meter`: true (boolean)
           + relationships (object) - related resources for customers
                + `correspondence-address` (AddressRelationship)
                    + data (object, required)
                        + id: `08937e42-49f0-4e11-90de-343c6b7f73c9` (string) - Id of related address
                        + type: `addresses` (string) - type of resource
                        
+ Response 400

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - specification version.
        + errors (array)
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.title.blank` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.first-name.blank` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.surname.blank` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.telephone-numbers.blank` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.email.blank` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.

+ Request invalid inputs

   + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca

   + Attributes
       + data (object, required)
           + type: customers (string)
           + attributes
                + title: Mr
                + `first-name`: "12323" (string)
                + surname: "3245" (string)
                + `date-of-birth`: `2008-09-15`
                + `telephone-numbers` (array)
                    + number: 01132578895, type: home, primary: true
                    + number: 0738178, type: mobile
                + `interested-in-smart-meter`: true (boolean)
                + email: kjoneailcom
           + relationships (object) - related resources for customers
                + `correspondence-address` (AddressRelationship)
                    + data (object, required)
                        + id: `08937e42-49f0-4e11-90de-343c6b7f73c9` (string) - Id of related address
                        + type: `addresses` (string) - type of resource
                        
+ Response 400

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - specification version.
        + errors (array)
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.first-name.invalid` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.surname.invalid` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.date-of-birth.invalid` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.telephone-number.invalid` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.client.email.invalid` (string).
               + status: 400 (string) - character-text equivalent of HTTP code.
               
+ Request unable to create customer

   + Headers

            content-type: application/vnd.api+json
            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca

   + Attributes
       + data (object, required)
           + type: customers (string)
           + attributes (Customer, required)
           + relationships (object) - related resources for customers
                + `correspondence-address` (AddressRelationship)
                    + data (object, required)
                        + id: `08937e42-49f0-4e11-90de-343c6b7f73c9` (string) - Id of related address
                        + type: `addresses` (string) - type of resource
                        
+ Response 500

    + Attributes (object)
        + jsonapi (object)
            + version: 1.0 (string) - specification version.
        + errors (array)
            + (object)
               + id: 1467732747181 (string) - an identifier for this error.
               + detail: `error.customers.not-found` (string).
               + status: 500 (string) - character-text equivalent of HTTP code.

## Update an Existing Customer [PATCH /v1/customers/{id}]
**Add** to a customer's existing telephone numbers or update their smart meter interest setting.
+ Request (application/vnd.api+json)

    + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca

    + Attributes
        + data (object, required)
            + type: customers (required, string)
            + id: 12345 (required, string)
            + attributes (object)
                + `telephone-numbers` (array[TelephoneNumber], optional)
                + `interested-in-smart-meter`: true (boolean, optional)

+ Response 204 (application/vnd.api+json)

+ Response 406 (application/vnd.api+json)
Fields other than telephone and smart meter may not be updated.

    + Attributes
        + jsonapi
            + version: 1.0 (string) - specification version.
        + errors
            + id: 1467732747181 - an identifier for this error.
            + detail: `error.customers.not-acceptable`.
            + status: 406 - character-text equivalent of HTTP code.

+ Response 404 (application/vnd.api+json)
Customer for update not found.

     + Attributes
        + jsonapi
            + version: 1.0 - specification version.
        + errors (array)
            + (object)
               + id: 1467732747181 - an identifier for this error.
               + detail: `error.customers.not-found`.
               + status: 404 - character-text equivalent of HTTP code.