FORMAT: 1A
HOST: http://api.britishgas.co.uk/v1

# New Boiler Bundle Orders

# Data structures

## Data (object, fixed)
- `id`: 1234 (string) - Entity Id
- `type` (string) - Entity type

## Links (object)
- `self` (string)
- `related` (string)

## Relationship (object)
- `data` (Data) - Data of an entity relationship

## ProductBundles (object)
+ jsonapi (object)
   + version: 1.0 (string, required) - version of the json api specifications.
+ data (Bundles)

## Allowance (object)
+ code: AW002 (string, required) - code of allowance type
+ name: £500.00 off your powerflush (string, required) - name of allowance
+ amount: 500.00 (string, required) - price of allowance

## Extra (object)
+ code: AW002 (string, required) - code of extra's.
+ name: Powerflush (string, required) - name of extra's.
+ amount: 500.00 (string, required) - price of extra's.
+ required: false (boolean, required) - need of extra's.

## Bundles (object)
+ is-address-used: `true` (boolean, required) - true if already lead created for address otherwise false
+ bundles (array[Bundle], optional) - list of allowed bundles if is-addresss-bundle is false otherwise null

## Bundle (object)
+ id: 002 (string, required) - id of bundle.
+ boile-code: CBLR0002 (string, required) - code of bundle.
+ boiler-name: Valiant ecoTech plus combi boiler (string, required) - name of boiler
+ total-gross-price: 2599.00 (string, required) - total gross price of bundle
+ total-bundle-Price: 2599.00 (string, required) - total price of bundle
+ total-price-after-discount: 1899.00 (string, required) - total price of bundle after discount
+ total-discount: 700.00 (string, required) - total discount of bundle
+ boiler-price: 1149.00 (string, required) - price of boiler
+ installation-price: 1114.00 (string, required) - price of bundle installation
+ extras (Extra) (array[Extra], required) - defination of extras 
+ allowances (Allowance) (array[Allowance], optional) - allowances of bundle

## LeadResponse (object)
+ `lead-reference` (string, optional)
+ `redirect-link` (string, optional) - Reason for failure
+ `token` (string, optional) - Reason for failure
+ `status` (string, optional) - Reason for failure

## CreateLeadResponse (object)
+ jsonapi (object)
   + version: 1.0 (string, required) - version of the json api specifications.
+ data (LeadResponse)

## Error (object)
+ id: `1528785614271`
+ detail: `error.client.bundle-details-not-found`
+ status : `404`

## ErrorResponse (object)
+ jsonapi (object)
   + version: 1.0 (string, required) - version of the json api specifications.
+ errors (array, required) - data format in fetch product catalogue will be returned.
   + (Error)

##  Product Bundle Details
New Boiler bundle details is used to fetch quotation for bundle from sales-froce system for requested bundles.

## Product Bundle orders [/v1/product-bundles/]

## Get Bundle Details [GET /product-bundles]

+ Request get bundles

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json
            identity-bundle: {"postcode": SK4 4HG, "bundles": [bundle1,bundle2], "isHomeCare": "Yes", "isPowerFlush": "Yes","extras":"[extra1,extra2]"}

+ Response 200 (application/vnd.api+json)

    + Body

            {
              "jsonapi": {
                "version": "1.0"
              },
              "data": {
                "id": "12345",
                "type": "Bundles",
                "attributes": {
                  "is-address-used": true,
                  "bundles": [
                    {
                      "id": "001",
                      "boilecode": "CBLR0002",
                      "boilerName": "Valiant ecoTech plus combi boiler",
                      "totalBundlePrice": "2599.00",
                      "boilerPrice": "1149.00",
                      "installPrice": "1114.00",
                      "optionalExtras": [
                        {
                          "name": "Powerflush",
                          "amount": "260.00",
                          "code": "PF001",
                          "required": "false"
                        }
                      ],
                      "allowances": [
                        {
                          "name": " £200.00 Homecare loyalty engineer discount",
                          "amount": "200.00",
                          "code": "AW004"
                        },
                        {
                          "name": " £50.00 off your powerflush",
                          "amount": "50.00",
                          "code": "AW002"
                        },
                        {
                          "name": "£50.00 off your magnetic system fiter",
                          "amount": "50.00",
                          "code": "AW003"
                        }
                      ]
                    },
                    {
                      "id": "002",
                      "boilecode": "CBLR0002",
                      "boilerName": "Valiant ecoTech plus combi boiler",
                      "totalBundlePrice": "2599.00",
                      "boilerPrice": "1149.00",
                      "installPrice": "1114.00",
                      "optionalExtras": [
                        {
                          "name": "Powerflush",
                          "amount": "260.00",
                          "code": "PF001",
                          "required": "false"
                        }
                      ],
                      "allowances": [
                        {
                          "name": " £200.00 Homecare loyalty engineer discount",
                          "amount": "200.00",
                          "code": "AW004"
                        },
                        {
                          "name": " £50.00 off your powerflush",
                          "amount": "50.00",
                          "code": "AW002"
                        },
                        {
                          "name": "£50.00 off your magnetic system fiter",
                          "amount": "50.00",
                          "code": "AW003"
                        }
                      ]
                    }
                  ]
                }
              }
            }
   

+ Request `invalid X-Client-ID`

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json

+ Response 403 (application/vnd.api+json)

   + Attributes (ErrorResponse)
      + errors (array)
         + (Error)
               + detail: `X-Client-ID not supplied!`
               + status: 403



## Validate Address For Existing Bundle Details [GET /product-bundles/{id}]
> `Note:` Appointments are not retrievable for CHI as soon as it is booked. While the status is still `intent-captured`, the client can GET an appointment.

+ Parameters

    + id: `123456` (string) - Id of selected address

+ Request get bundles

   + Headers

            x-client-id: `cbdcfa43-dd67-4c38-b418-83572a936fca`
            content-type: application/vnd.api+json

    + Body

            {
                  "CustomerData": {
                    "customerDetails": {
                      "Salutation": "Miss",
                      "LastName": "Mcamullan",
                      "FirstName": "Catherine "
                    },
                    "contactDetails": {
                      "MobilePhone": null,
                      "Email": "cmac14@virginmedia.com"
                    },
                    "Address": {
                      "TownCity": "LEEDS",
                      "Street": "EDINBURGH PLACE",
                      "PostCode": "LS12 3RQ",
                      "NameNumber": "14",
                      "CountyProvince": ""
                    },
                    "chiLeadChannel": "Online",
                    "resStatus": "Owner",
                    "productInterest": "Online Boiler",
                    "mediaCode": "ENGI",
                    "marketingPreference": "EMAIL",
                    "isMarketingConsent": "Yes",
                    "asbestosIdentified": "No",
                    "isHomecare": "Yes",
                    "isPowerflush": "No",
                    "fuelType": "Natural Gas"
                  },
                  "bundle": [
                    {
                      "id": "001",
                      "boilerCode": "CBLR0001",
                      "totalGrossPrice": "2599.00",
                      "totalDiscount": "700.00",
                      "totalPriceAfterDicount": "1899.00",
                      "extrasSold": [
                        {
                          "name": "Powerflush",
                          "amount": "260.00",
                          "code": "PF001"
                        }
                      ],
                      "allowancesApplied": [
                        {
                          "name": "£200.00 Homecare loyalty engineer discount",
                          "amount": "200.00",
                          "code": "AW004"
                        },
                        {
                          "name": "£50.00 off your powerflush",
                          "amount": "500.00",
                          "code": "AW002"
                        }
                      ]
                    }
                  ]
            }
            
+ Response 200 (application/vnd.api+json)

    + Body

            {
              "jsonapi": {
                "version": "1.0"
              },
              "data": {
                "id": "12345",
                "type": "Bundles",
                "attributes": {
                  "is-address-used": true,
                  "bundles": []
                    
                }
              }
            }
   

+ Request `invalid X-Client-ID`

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json

+ Response 403 (application/vnd.api+json)

   + Attributes (ErrorResponse)
      + errors (array)
         + (Error)
               + detail: `X-Client-ID not supplied!`
               + status: 403

+ Request backend failure

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json

+ Response 424 (application/vnd.api+json)

   + Attributes (ErrorResponse)
      + errors (array)
         + (Error)
               + detail: dependency failure
               + status: 424

## Group Create Bundle Lead
Create Bundle Customer end point is used to create a lead in salesforce system for selected bundle by customer.
## Create Bundle Lead [`/v1/bundle-lead`]

## Create Bundle Orders [POST /bundle-lead]

+ Request create bundle lead 

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json
    + Body 
    
    

+ Response 201 (application/vnd.api+json)

   + Attributes (CreateLeadResponse)

+ Request `invalid X-Client-ID`

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json

+ Response 403 (application/vnd.api+json)

   + Attributes (ErrorResponse)
      + errors (array)
         + (Error)
               + detail: `X-Client-ID not supplied!`
               + status: 403

+ Request backend failure

   + Headers

            x-client-id: cbdcfa43-dd67-4c38-b418-83572a936fca
            content-type: application/vnd.api+json

+ Response 424 (application/vnd.api+json)

   + Attributes (ErrorResponse)
      + errors (array)
         + (Error)
               + detail: dependency failure
               + status: 424